version: "3"

tasks:
  run:
    desc: "Run program"
    cmds:
      - cmd: cd build && docker compose up -d
      - cmd: rm -rf debug.log
        ignore_error: true
      - go run .
  logs:
    desc: "Run program"
    cmds:
      - cmd: tail -f debug.log
  gen:
    desc: "Generate mocks"
    cmds:
      - cmd: go generate ./...
  sqlite:
    desc: "Re-init SQLite DB"
    cmds:
      - rm -rf ./test.db
      - touch ./test.db
      - sqlite3 ./test.db < ./build/sqlite/init.sql
