version: "3"

tasks:
  run:
    desc: "Run program"
    cmds:
      - cmd: rm -rf debug.log
        ignore_error: true
      - go run .
  logs:
    desc: "Run program"
    cmds:
      - cmd: tail -f debug.log
